version: '3.3'
services:

  site:
    build:
      context: django
      dockerfile: ../environments/site/Dockerfile
      args:
        UNAME: ${UNAME:-www}
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    image: example-site:latest
    restart: "unless-stopped"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-False}
      - DJANGO_POSTGRES_DB=${DJANGO_POSTGRES_DB}
      - DJANGO_POSTGRES_USER=${DJANGO_POSTGRES_USER}
      - DJANGO_POSTGRES_PASSWORD=${DJANGO_POSTGRES_PASSWORD}

    # TODO: Is it always safe to do this?  Is it sane?
    # TODO: How can we better make this wait for the database container to be ready?
    command: /bin/bash -c "sleep 10 && cd /var/www && python manage.py makemigrations && python manage.py migrate && gunicorn -c conf/gunicorn/conf.py"
    ports:
      - 8000:8000
    depends_on: ["db"]

  db:
    image: postgres:14-bullseye
    restart: "unless-stopped"
    environment:
      - POSTGRES_DB=${DJANGO_POSTGRES_DB}
      - POSTGRES_USER=${DJANGO_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DJANGO_POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    # TODO: This seemed to be necessary to get the site container to access it.  Why?
    ports:
      - 5432:5432

  nginx:
    build:
      context: environments/nginx
      dockerfile: Dockerfile
    image: example-nginx:latest
    restart: "unless-stopped"
    environment:
      - GUNICORN_LOGLEVEL=${GUNICORN_LOGLEVEL:-info}
      - GUNICORN_DEBUG=${GUNICORN_DEBUG:-False}
    ports:
      - 80:80
      - 443:443
    depends_on: ["site"]

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: "unless-stopped"
    links: ["db"]
    depends_on: ["db"]
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${DJANGO_POSTGRES_DB}
      - POSTGRES_USER=${DJANGO_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DJANGO_POSTGRES_PASSWORD}
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8181
