version: '3.8'
services:

  site:
    build:
      context: testsite
      dockerfile: ../environments/site/Dockerfile
      args:
        UNAME: ${UNAME:-www}
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    image: site:latest
    restart: "unless-stopped"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
    # TODO: Is it always safe to do this?  Is it sane?
    command: /bin/bash -c "cd /var/www && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000

