version: '3.3'
services:

  site:
    build:
      context: testsite
      dockerfile: ../environments/site/Dockerfile
      args:
        UNAME: ${UNAME:-www}
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    image: site:latest
    restart: "unless-stopped"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_POSTGRES_DB=${DJANGO_POSTGRES_DB}
      - DJANGO_POSTGRES_USER=${DJANGO_POSTGRES_USER}
      - DJANGO_POSTGRES_PASSWORD=${DJANGO_POSTGRES_PASSWORD}

    # TODO: Is it always safe to do this?  Is it sane?
    # TODO: How can we better make this wait for the database container to be ready?
    command: /bin/bash -c "sleep 10 && cd /var/www && python manage.py makemigrations && python manage.py migrate && gunicorn -c conf/gunicorn/conf.py"
    ports:
      - 8000:8000
    depends_on: ["db"]

  db:
    image: postgres:14-bullseye
    restart: "unless-stopped"
    environment:
      - POSTGRES_DB=${DJANGO_POSTGRES_DB}
      - POSTGRES_USER=${DJANGO_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DJANGO_POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - 5432:5432
