name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Everything
        run: python test.py
  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Everything
        run: python test.py
   
